

NOD = 100

CHUNK_SIZE = 400
CHUNK_OVERLAP = 40

TOP_K_PER_ANCHOR = 10
CANDIDATE_POOL_SIZE = 30


#RAG & AGENT

TOP_K = 7
MODEL = "mistralai/Mistral-7B-Instruct-v0.3"
MAX_NEW_TOKENS_AGENT = 4000
MAX_NEW_TOKENS_RAG = 600
TEMPERATURE = 0.4
TOP_P = 0.9
NO_REPEAT_NGRAM_SIZE = 3
REPETITION_PENALTY = 1.1
DO_SAMPLE = True